networks:
  monitoring:

volumes:
  grafana_data:
  prometheus_data:

services:  
  
  grafana:
    image: grafana/grafana:9.1.6
    container_name: nutbox-grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning/datasources
    env_file:
      - ./grafana/.env
    ports:
      - 3000:3000
    networks:
      monitoring:
        aliases: 
          - grafana
    
  prometheus:
    image: prom/prometheus:latest
    container_name: nutbox-prometheus
    restart: always
    healthcheck:
      test: wget --spider localhost:9090 || exit 1
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 5s
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=360h'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring
  
  jmeter:
    container_name: nutbox-jmeter
    depends_on:
      prometheus:
        condition: service_healthy
    build:
      context: ./jmeter
      dockerfile: Dockerfile
      args:
        - JVM_ARGS=$JVM_ARGS
    volumes:
      - ./logs/results/client:/jmeter/results
    ports:
      - 9270:9270
    networks:
      - monitoring