global:
  scrape_interval: 5s
  evaluation_interval: 2s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: 'nutbox-jmeter'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['nutbox-jmeter:9270']
  
  - job_name: 'nutbox-service'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['54.233.219.114:9100']